CREATE DATABASE EMPLEADOS;

USE EMPLEADOS


CREATE TABLE TIPODOCUMENTO
(
    IDTIPODOCUMENTO INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    DOCUMENTO VARCHAR(50) NOT NULL,
    LONGITUD INT NOT NULL,
    FECHAINSERTO DATETIME NOT NULL,
    BORRADO BIT NOT NULL DEFAULT 0
);

CREATE TABLE DOCUMENTO
(
    IDDOCUMENTO INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    NDOCUMENTO VARCHAR(50) NOT NULL,
    FKTIPODOCUMENTO INT NOT NULL,
    FECHAINSERTO DATETIME NOT NULL,
    BORRADO BIT NOT NULL DEFAULT 0,
    FOREIGN KEY(FKTIPODOCUMENTO) REFERENCES TIPODOCUMENTO(IDTIPODOCUMENTO)
);


CREATE TABLE AREA
(
    IDAREA INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    AREA VARCHAR(50) NOT NULL,
    BORRADO BIT NOT NULL DEFAULT 0,
    FECHAINSERTO DATETIME NOT NULL
);

CREATE TABLE SUBAREA
(
    IDSUBAREA INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    SUBAREA VARCHAR(50) NOT NULL,
    FKAREA INT NOT NULL,
    BORRADO BIT NOT NULL DEFAULT 0,
    FECHAINSERTO DATETIME NOT NULL,
    FOREIGN KEY(FKAREA) REFERENCES AREA(IDAREA)
);

CREATE TABLE EMPLEADO
(
    IDEMPLEADO  INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    PRIMERNOMBRE VARCHAR(50) NOT NULL,
    SEGUNDONOMBRE VARCHAR(50) NOT NULL,
    PRIMERAPELLIDO VARCHAR(50) NOT NULL,
    SEGUNDOAPELLIDO VARCHAR(50) NOT NULL,
    NDOCUMENTO VARCHAR(10) NOT NULL,
    FKTIPODOCUMENTO INT NOT NULL,
    FKSUBAREA INT NOT NULL,
    BORRADO BIT NOT NULL DEFAULT 0,
    FECHAINSERTO DATETIME NOT NULL,
    FOREIGN KEY(FKTIPODOCUMENTO) REFERENCES TIPODOCUMENTO(IDTIPODOCUMENTO),
    FOREIGN KEY(FKSUBAREA) REFERENCES SUBAREA(IDSUBAREA)
);
